name: DynamoDB Refresh

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  workflow_dispatch:  # Manual trigger

jobs:
  dynamodb-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run DynamoDB Refresh
        run: |
          sed -i 's/replace-bucket-name/${{ secrets.S3BUCKET }}/g' dynamoDB-refresh/blog-posts.json
          python dynamoDB-refresh/dynamo-table-refresh.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DYNAMODB_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DYNAMODB_SECRET_KEY }}
